### ISSUE TITLE
Enter password of zipfiles

### ISSUE THREAD

**Issue by solokilla** [STARK-404/Whatsapp-spy#3]
![Screenshot_20231001-193022](https://github.com/STARK-404/Whatsapp-spy/assets/54829953/2a46d350-9d49-4f6e-919b-451cd03ca496)
What's the password of the Zip files?

**Comment by STARK-404** [comment]
Password is paid bro are you interested to buy?
Proof/tutorial :-
https://drive.google.com/file/d/16th3-eRbWwKzmQa8TXKSBkjYhcIM26eC/view?usp=drivesdk

**Comment by Muzamil-stack** [comment]
I want zip file code ?

**Comment by STARK-404** [comment]
Want zip code just pay bro....

**Comment by Muzamil-stack** [comment]
I want zip code but how i can pay you bro ?

**Comment by STARK-404** [comment]
Which is your country ? 
Amount 18$

**Comment by Muzamil-stack** [comment]
Im in Afghanistan.
So how i can pay you ?

**Comment by STARK-404** [comment]
Crypto? Amazon.in giftcard or bank transfer

**Comment by Muzamil-stack** [comment]
But that's not allowed in my country

**Comment by Muzamil-stack** [comment]
Give me your WhatsApp number then i will describe you how i can pay you

**Comment by STARK-404** [comment]
Wa.me//+919072233245

**Comment by tacitur** [comment]
Me interesa
